### ISSUE TITLE
Cannot pull from custom repository

### ISSUE THREAD

**Issue by WTFKr0** [kevana/ui-for-docker#213]
I cannot pull images from a local repo, i Got in the UI : 

Cannot pull image myrepo:5000/user/image:latest Reason: Error: image library/image not found
When i do : 
docker pull myrepo:5000/user/image:latest, it works

Got no problem to pull from dockerhub
Any clue ?

**Comment by kevana** [comment]
Could you post the ajax request/response that's sent from the browser? URL should be something like `POST /dockerapi/images/create`

**Comment by WTFKr0** [comment]
Docker : Server Version: 1.11.1
APP : uifd/ui-for-docker   latest   c2b1b90a9e75        4 weeks ago         7.391 MB

I hv change information by myrepo/user/image for confidentiality

Ajax request : 
/dockerapi/images/create?fromImage=image&registry=myrepo:5000&repo=user&tag=latest

Response : 
{"status":"Pulling repository docker.io/library/image"}
{"errorDetail":{"message":"Error: image library/image not found"},"error":"Error: image library/image not found"}

On docker.log, we see docker go to dockerhub : 
Trying to pull base from https://registry-1.docker.io v2"
Log : 
time="2016-06-02T16:09:45.542570860Z" level=debug msg="Calling POST /images/create?fromImage=image&registry=myrepo:5000&
repo=user&tag=latest"
time="2016-06-02T16:09:45.542868362Z" level=debug msg="form data: {\"fromImage\":\"image\",\"registry\":\"myrepo:5000\",
\"repo\":\"user\",\"tag\":\"latest\"}"
time="2016-06-02T16:09:45.542993550Z" level=debug msg="Trying to pull image from https://registry-1.docker.io v2"
time="2016-06-02T16:09:46.781016833Z" level=debug msg="Increasing token expiration to: 60 seconds"
time="2016-06-02T16:09:47.627281102Z" level=error msg="Attempting next endpoint for pull after error: unauthorized: authentication required"

time="2016-06-02T16:09:47.627339399Z" level=debug msg="Trying to pull image from https://index.docker.io v1"
time="2016-06-02T16:09:47.627359152Z" level=debug msg="hostDir: /etc/docker/certs.d/docker.io"
time="2016-06-02T16:09:47.627854832Z" level=debug msg="[registry] Calling GET https://index.docker.io/v1/repositories/library/image/images"
time="2016-06-02T16:09:48.316626090Z" level=error msg="Not continuing with pull after error: Error: image library/image not found"

**Comment by deviantony** [comment]
I suspect that this features never worked.

The current implementation for pulling an image refers to a `registry` parameter to pull an image from a registry.

See: https://github.com/kevana/ui-for-docker/blob/master/app/shared/services.js#L92

However, there is no `registry` parameter in the latest Docker API: https://docs.docker.com/engine/reference/api/docker_remote_api_v1.23/#create-an-image

I've reviewed API changes from 1.18 to 1.23 and I did not seen any `registry` parameter.

In order to pull an image from a private registry, I think that we'll have to use the Registry API: https://docs.docker.com/registry/spec/api/#pulling-an-image

**Comment by deviantony** [comment]
I've classified this one as a new-feature, as it is not possible to pull an image from a custom repository at the moment.
